# Generated by Django 5.1.7 on 2025-03-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TruckSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('load_day', models.CharField(max_length=20)),
                ('load_start_time', models.TimeField()),
                ('load_complete_time', models.TimeField()),
                ('depart_day', models.CharField(max_length=20)),
                ('depart_time', models.TimeField()),
                ('arrive_day', models.CharField(max_length=20)),
                ('arrive_time', models.TimeField()),
                ('unload_day', models.CharField(max_length=20)),
                ('unload_time', models.TimeField()),
                ('transit_time', models.CharField(max_length=50)),
            ],
        ),
    ]
